version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  flask-monitoring:

services:
  ## Flask app ##
  flask-app:
    image: asbogolepov/flask-monitoring
    container_name: flask-app
    ports:
      - 80:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1s
      timeout: 3s
      retries: 60
    restart: always  
    networks:
      - flask-monitoring

  ## Prometheus ##  
  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - flask-monitoring
    restart: always
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - flask-monitoring
    restart: always
    command: "grafana-cli admin reset-admin-password admin"